export const heroes = [
  {
    "name": "Aisling",
    "key": "aisling",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/aisling.png",
    "color": "#8a2248",
  },
  {
    "name": "Beckett",
    "key": "beckett",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/beckett.png",
    "color": "",
  },
  {
    "name": "Charnok",
    "key": "charnok",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/charnok.png",
    "color": "",
  },
  {
    "name": "Griselma",
    "key": "griselma",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/griselma.png",
    "color": "",
  },
  {
    "name": "HK-206",
    "key": "hk_206",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/hk_206.png",
    "color": "",
  },
  {
    "name": "Imani",
    "key": "imani",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/imani.png",
    "color": "",
  },
  {
    "name": "Lord Knossos",
    "key": "lord_knossos",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/lord_knossos.png",
    "color": "#aa958e",
  },
  {
    "name": "Mozu",
    "key": "mozu",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/mozu.png",
    "color": "#ff6200",
  },
  {
    "name": "Pakko",
    "key": "pakko",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/pakko.png",
    "color": "#9adbf4",
  },
  {
    "name": "Ramsay",
    "key": "ramsay",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/ramsay.png",
    "color": "#6f6fae",
  },
  {
    "name": "The Margrave",
    "key": "the_margrave",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/the_margrave.png",
    "color": "#333",
  },
  {
    "name": "Tripp",
    "key": "tripp",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/tripp.png",
    "color": "#1561b3",
  },
  {
    "name": "Tyto the Swift",
    "key": "tyto",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/tyto.png",
    "color": "#9a0025",
  },
  {
    "name": "Uncle Sven",
    "key": "uncle_sven",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/uncle_sven.png",
    "color": "",
  },
  {
    "name": "Vadasi",
    "key": "vadasi",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/vadasi.png",
    "color": "#d9a93e",
  },
  {
    "name": "Voden",
    "key": "voden",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/voden.png",
    "color": "#6e994d",
  },
  {
    "name": "Wu",
    "key": "wu",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/wu.png",
    "color": "#22aab7",
  },
  {
    "name": "Xenobia",
    "key": "xenobia",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/xenobia.png",
    "color": "#8e5ab5",
  },
  {
    "name": "Zandora",
    "key": "zandora",
    "image": "https://stats.gogigantic.com/images/gigantic-careers/user/zandora.png",
    "color": "#f982f9",
  }
];
